# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

st.set_page_config(page_title="Deloitte SEC Chatbot", layout="wide")

# --- Custom CSS for rounded containers ---

st.markdown(
    """
    <style>
    .rounded-title {
        background-color: #111;
        color: #fff;
        padding: 0 28px;
        height: 72px;
        display: flex;
        align-items: center;
        border-bottom: 2px solid #222;
        box-shadow: 0 2px 6px rgba(0,0,0,0.08);
        margin-bottom: 0px;
        border-radius: 18px;
    }
    .rounded-logo {
        background-color: #111;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 72px;
        border-radius: 18px;
        margin-right: 8px;
    }
    .rounded-logo img {
        border-radius: 12px;
        background: #222;
        padding: 4px;
    }
    </style>
    """,
    unsafe_allow_html=True
)
col_logo, col_title = st.columns([1, 8])
with col_logo:
    st.image("images/Deloitte.png", width=85)
with col_title:
    st.markdown("""
        <div style="background-color: #111; color: #fff; padding: 0 20px; height: 52px; display: flex; align-items: center; border-bottom: 2px solid #222; box-shadow: 0 2px 6px rgba(0,0,0,0.08); margin-bottom: 0px; border-radius: 18px;">
            <h1 style="color: #fff; margin: 2; font-size: 2rem; font-family: 'Segoe UI', Arial, sans-serif;">
                SEC Filing Chatbot
            </h1>
        </div>
    """, unsafe_allow_html=True)